### ISSUE TITLE
Wiki RequestAccount page broken

### ISSUE THREAD

**Issue by rcsheets** [sudoroom/sudo-infrastructure#1]
The "Request an account" link at the top of the [Sudo Room wiki](https://sudoroom.org/wiki/Sudoroom) leads to a [blank page](https://sudoroom.org/wiki/Special:RequestAccount).

_Originally reported by Corey Johns corey@x64.co via the sudo-discuss mailing list._

**Comment by rcsheets** [comment]
I enabled logging for the wiki fpm pool. This is what gets logged when I hit the "Request an account" link:

`[22-Sep-2016 23:50:27 America/Los_Angeles] PHP Catchable fatal error:  Argument 1 passed to QuestyCaptcha::getForm() must be an instance of OutputPage, none given, called in /home/wiki/public_html/mediawiki/extensions/ConfirmAccount/frontend/specialpages/actions/RequestAccount_body.php on line 231 and defined in /home/wiki/public_html/mediawiki/extensions/ConfirmEdit/QuestyCaptcha/QuestyCaptcha.class.php on line 44`

**Comment by rcsheets** [comment]
The error being reported is that `getForm()` is being called with no arguments, but there is a required argument. However, reading the (quite short) `getForm()` function shows that the required argument is never actually used.

I removed the argument from the function definition and that fixed the problem.

**Comment by yardenac** [comment]
After updating the wiki to 1.27.1, the new upstream function looks like this:

   `function getForm( OutputPage $out, $tabIndex = 1 ) {`

$tabIndex is actually used this time. Not sure what to do. I'm going to hold off on backporting this change until I look closer at it.

**Comment by rcsheets** [comment]
`$tabIndex` has a default there. Is `$out` used?
