### ISSUE TITLE
Wiki account approvals are broken

### ISSUE THREAD

**Issue by rcsheets** [sudoroom/sudo-infrastructure#3]
When attempting to approve a wiki account request, the following warning is logged:

`PHP Warning:  failed to mkdir "/accountcreds/s/su/sud" mode 0777 [Called from wfMkdirParents in /home/wiki/public_html/mediawiki/includes/GlobalFunctions.php at line 2551] in /home/wiki/public_html/mediawiki/includes/debug/MWDebug.php on line 300`

Additionally, the confirmation page (seen by the bureaucrat confirming the account) displays the following error message:

`Could not create directory "mwstore://accountcreds-backend/accountcreds-public/s/su/sud".`

**Comment by rcsheets** [comment]
Looks like it should be trying to create `/home/wiki/public_html/mediawiki/images/accountcreds/s/su/sud` (which already exists) rather than `/accountcreds/s/su/sud`. Some relevant prefix setting must be missing or broken.

**Comment by rcsheets** [comment]
Upload paths aren't universally broken, since file uploads work OK. Just uploaded https://sudoroom.org/wiki/File:640px-Flag_of_Togo.svg.png as a test. So looks like the problem is isolated to the ConfirmAccount extension.

**Comment by rcsheets** [comment]
Fixed by explicitly setting `$wgConfirmAccountFSRepos` in `LocalSettings.php`.

**Comment by Juul** [comment]
Nice :D
